INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-46', 'initiative', NULL, 'Act on live-session improvement briefing (pql-improvements.md)', NULL, 'backlog', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '77cc9b623ec959ce69c4eaeea6f7fe64', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-47', 'task', 'T-46', 'Write-through ticket mutations to the changelog (#1)', NULL, 'backlog', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '9439b5f6fcea5200d10ee2747d8cfa41', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-48', 'task', 'T-46', 'Fix embedded skill durability section (#2)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '7bb96c46c3113717de5408f656cddc38', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-49', 'task', 'T-46', 'Rewrite schema-mismatch recovery hint (#3/#4)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '0c34ad709586032dcfe9223885545e43', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-50', 'task', 'T-46', 'Add ''ticket new --id-only'' for tree-creation scripts (#5)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'c8a1d716927fe2102858a16202baec9a', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-51', 'task', 'T-46', 'Regression tests: resolved-question index idempotency + skill/binary flag parity (#6/#7)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '62c6b81be585398cbfcaa9ce9131c68d', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-50', 'task', 'T-46', 'Add ''ticket new --id-only'' for tree-creation scripts (#5)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '1a24166e7266ccaf2c67eab9902f8fec', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-49', 'task', 'T-46', 'Rewrite schema-mismatch recovery hint (#3/#4)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '391ff9672b4e5af5456a59c98ff943c7', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-48', 'task', 'T-46', 'Fix embedded skill durability section (#2)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'ae675e5bd570ef4293a80336301c06d7', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-51', 'task', 'T-46', 'Regression tests: resolved-question index idempotency + skill/binary flag parity (#6/#7)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'e32727e26c2241ae59dbebb1ba937289', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-47', 'task', 'T-46', 'Write-through ticket mutations to the changelog (#1)', NULL, 'done', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'e89b4c3944518dda9a9f4dbd46338b48', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-46', 'initiative', NULL, 'Act on live-session improvement briefing (pql-improvements.md)', NULL, 'done', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:36', NULL, 'd14de882b675d9c03a23a4ce4f03580c', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-52', 'task', NULL, 'Unify .githooks shim tracking: post-checkout/post-rewrite still tracked, pre-commit/post-merge ignored', 'The four pql replication hook shims in .githooks/ are tracked inconsistently:

  - .githooks/post-checkout  -> TRACKED (git ls-files)
  - .githooks/post-rewrite   -> TRACKED
  - .githooks/pre-commit     -> gitignored (.gitignore L65)
  - .githooks/post-merge     -> gitignored (.gitignore L66)

All four are functionally identical static two-line shims (git rev-parse + source .pql/hooks/<name>); none bakes a per-developer path (that lives in the .pql/hooks/* bodies, correctly ignored under .pql/*). So the split is unintended drift, not a real distinction. (pre-push is legitimately tracked -- it is the hand-authored lint gate, not a replication shim.)

History: T-28/T-38/T-39 settled that hook scripts + shims are per-clone, planted by ''pql init'', not tracked; T-39 git-rm''d .pql/hooks/ and dropped the !.pql/hooks/ exception. T-30 (cancelled) records that ensureGitHookShim is supposed to plant ALL FOUR .githooks/ shims and that post-checkout/post-rewrite were the ones being missed. The tracked post-checkout/post-rewrite shims are the leftover that escaped the T-39 cleanup, and .gitignore lacks matching ignore rules for them.

Impact: latent. A fresh clone that only runs ''git config core.hooksPath .githooks'' (without ''pql init'') gets pre-push + the two tracked rebuild shims, but NOT pre-commit/post-merge -- so write-through staging and post-merge import silently don''t fire until init runs. The asymmetry also makes the per-clone-hooks invariant (T-28) ambiguous.

Proposed resolution (align to the settled per-clone policy): git rm .githooks/post-checkout and .githooks/post-rewrite, add them to the .gitignore stanza alongside pre-commit/post-merge, and ensure ''pql init'' (ensureGitHookShim) reliably plants all four shims. Confirm a fresh clone + ''pql init'' + core.hooksPath=.githooks yields the full lifecycle with a clean tree. Alternatively, if committed shims are deemed desirable for zero-init clones, commit all four and document why -- but that contradicts T-28/T-39, so it would need a D-18 amendment.

Surfaced 2026-06-05 while wiring core.hooksPath on the pql repo: pre-commit/post-merge were absent from the active hook set until ''pql init'' planted them.', 'backlog', 'medium', NULL, NULL, 'D-18', '2026-06-05 10:44:32', '2026-06-05 10:44:32', NULL, '28f6f22e141e650f42060d1598157bd4', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
