INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-46', 'initiative', NULL, 'Act on live-session improvement briefing (pql-improvements.md)', NULL, 'backlog', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '77cc9b623ec959ce69c4eaeea6f7fe64', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-47', 'task', 'T-46', 'Write-through ticket mutations to the changelog (#1)', NULL, 'backlog', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '9439b5f6fcea5200d10ee2747d8cfa41', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-48', 'task', 'T-46', 'Fix embedded skill durability section (#2)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '7bb96c46c3113717de5408f656cddc38', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-49', 'task', 'T-46', 'Rewrite schema-mismatch recovery hint (#3/#4)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '0c34ad709586032dcfe9223885545e43', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-50', 'task', 'T-46', 'Add ''ticket new --id-only'' for tree-creation scripts (#5)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'c8a1d716927fe2102858a16202baec9a', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-51', 'task', 'T-46', 'Regression tests: resolved-question index idempotency + skill/binary flag parity (#6/#7)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '62c6b81be585398cbfcaa9ce9131c68d', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-50', 'task', 'T-46', 'Add ''ticket new --id-only'' for tree-creation scripts (#5)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '1a24166e7266ccaf2c67eab9902f8fec', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-49', 'task', 'T-46', 'Rewrite schema-mismatch recovery hint (#3/#4)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '391ff9672b4e5af5456a59c98ff943c7', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-48', 'task', 'T-46', 'Fix embedded skill durability section (#2)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'ae675e5bd570ef4293a80336301c06d7', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-51', 'task', 'T-46', 'Regression tests: resolved-question index idempotency + skill/binary flag parity (#6/#7)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'e32727e26c2241ae59dbebb1ba937289', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-47', 'task', 'T-46', 'Write-through ticket mutations to the changelog (#1)', NULL, 'done', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, 'e89b4c3944518dda9a9f4dbd46338b48', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-46', 'initiative', NULL, 'Act on live-session improvement briefing (pql-improvements.md)', NULL, 'done', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:36', NULL, 'd14de882b675d9c03a23a4ce4f03580c', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-52', 'task', NULL, 'Unify .githooks shim tracking: post-checkout/post-rewrite still tracked, pre-commit/post-merge ignored', 'The four pql replication hook shims in .githooks/ are tracked inconsistently:

  - .githooks/post-checkout  -> TRACKED (git ls-files)
  - .githooks/post-rewrite   -> TRACKED
  - .githooks/pre-commit     -> gitignored (.gitignore L65)
  - .githooks/post-merge     -> gitignored (.gitignore L66)

All four are functionally identical static two-line shims (git rev-parse + source .pql/hooks/<name>); none bakes a per-developer path (that lives in the .pql/hooks/* bodies, correctly ignored under .pql/*). So the split is unintended drift, not a real distinction. (pre-push is legitimately tracked -- it is the hand-authored lint gate, not a replication shim.)

History: T-28/T-38/T-39 settled that hook scripts + shims are per-clone, planted by ''pql init'', not tracked; T-39 git-rm''d .pql/hooks/ and dropped the !.pql/hooks/ exception. T-30 (cancelled) records that ensureGitHookShim is supposed to plant ALL FOUR .githooks/ shims and that post-checkout/post-rewrite were the ones being missed. The tracked post-checkout/post-rewrite shims are the leftover that escaped the T-39 cleanup, and .gitignore lacks matching ignore rules for them.

Impact: latent. A fresh clone that only runs ''git config core.hooksPath .githooks'' (without ''pql init'') gets pre-push + the two tracked rebuild shims, but NOT pre-commit/post-merge -- so write-through staging and post-merge import silently don''t fire until init runs. The asymmetry also makes the per-clone-hooks invariant (T-28) ambiguous.

Proposed resolution (align to the settled per-clone policy): git rm .githooks/post-checkout and .githooks/post-rewrite, add them to the .gitignore stanza alongside pre-commit/post-merge, and ensure ''pql init'' (ensureGitHookShim) reliably plants all four shims. Confirm a fresh clone + ''pql init'' + core.hooksPath=.githooks yields the full lifecycle with a clean tree. Alternatively, if committed shims are deemed desirable for zero-init clones, commit all four and document why -- but that contradicts T-28/T-39, so it would need a D-18 amendment.

Surfaced 2026-06-05 while wiring core.hooksPath on the pql repo: pre-commit/post-merge were absent from the active hook set until ''pql init'' planted them.', 'backlog', 'medium', NULL, NULL, 'D-18', '2026-06-05 10:44:32', '2026-06-05 10:44:32', NULL, '28f6f22e141e650f42060d1598157bd4', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-52', 'task', NULL, 'Unify .githooks shim tracking: post-checkout/post-rewrite still tracked, pre-commit/post-merge ignored', 'The four pql replication hook shims in .githooks/ are tracked inconsistently:

  - .githooks/post-checkout  -> TRACKED (git ls-files)
  - .githooks/post-rewrite   -> TRACKED
  - .githooks/pre-commit     -> gitignored (.gitignore L65)
  - .githooks/post-merge     -> gitignored (.gitignore L66)

All four are functionally identical static two-line shims (git rev-parse + source .pql/hooks/<name>); none bakes a per-developer path (that lives in the .pql/hooks/* bodies, correctly ignored under .pql/*). So the split is unintended drift, not a real distinction. (pre-push is legitimately tracked -- it is the hand-authored lint gate, not a replication shim.)

History: T-28/T-38/T-39 settled that hook scripts + shims are per-clone, planted by ''pql init'', not tracked; T-39 git-rm''d .pql/hooks/ and dropped the !.pql/hooks/ exception. T-30 (cancelled) records that ensureGitHookShim is supposed to plant ALL FOUR .githooks/ shims and that post-checkout/post-rewrite were the ones being missed. The tracked post-checkout/post-rewrite shims are the leftover that escaped the T-39 cleanup, and .gitignore lacks matching ignore rules for them.

Impact: latent. A fresh clone that only runs ''git config core.hooksPath .githooks'' (without ''pql init'') gets pre-push + the two tracked rebuild shims, but NOT pre-commit/post-merge -- so write-through staging and post-merge import silently don''t fire until init runs. The asymmetry also makes the per-clone-hooks invariant (T-28) ambiguous.

Proposed resolution (align to the settled per-clone policy): git rm .githooks/post-checkout and .githooks/post-rewrite, add them to the .gitignore stanza alongside pre-commit/post-merge, and ensure ''pql init'' (ensureGitHookShim) reliably plants all four shims. Confirm a fresh clone + ''pql init'' + core.hooksPath=.githooks yields the full lifecycle with a clean tree. Alternatively, if committed shims are deemed desirable for zero-init clones, commit all four and document why -- but that contradicts T-28/T-39, so it would need a D-18 amendment.

Surfaced 2026-06-05 while wiring core.hooksPath on the pql repo: pre-commit/post-merge were absent from the active hook set until ''pql init'' planted them.', 'in_progress', 'medium', NULL, NULL, 'D-18', '2026-06-05 10:44:32', '2026-06-05 11:00:56', NULL, 'dc4439ff11bec7a2595501b0daf175e2', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-52', 'task', NULL, 'Unify .githooks shim tracking: post-checkout/post-rewrite still tracked, pre-commit/post-merge ignored', 'The four pql replication hook shims in .githooks/ are tracked inconsistently:

  - .githooks/post-checkout  -> TRACKED (git ls-files)
  - .githooks/post-rewrite   -> TRACKED
  - .githooks/pre-commit     -> gitignored (.gitignore L65)
  - .githooks/post-merge     -> gitignored (.gitignore L66)

All four are functionally identical static two-line shims (git rev-parse + source .pql/hooks/<name>); none bakes a per-developer path (that lives in the .pql/hooks/* bodies, correctly ignored under .pql/*). So the split is unintended drift, not a real distinction. (pre-push is legitimately tracked -- it is the hand-authored lint gate, not a replication shim.)

History: T-28/T-38/T-39 settled that hook scripts + shims are per-clone, planted by ''pql init'', not tracked; T-39 git-rm''d .pql/hooks/ and dropped the !.pql/hooks/ exception. T-30 (cancelled) records that ensureGitHookShim is supposed to plant ALL FOUR .githooks/ shims and that post-checkout/post-rewrite were the ones being missed. The tracked post-checkout/post-rewrite shims are the leftover that escaped the T-39 cleanup, and .gitignore lacks matching ignore rules for them.

Impact: latent. A fresh clone that only runs ''git config core.hooksPath .githooks'' (without ''pql init'') gets pre-push + the two tracked rebuild shims, but NOT pre-commit/post-merge -- so write-through staging and post-merge import silently don''t fire until init runs. The asymmetry also makes the per-clone-hooks invariant (T-28) ambiguous.

Proposed resolution (align to the settled per-clone policy): git rm .githooks/post-checkout and .githooks/post-rewrite, add them to the .gitignore stanza alongside pre-commit/post-merge, and ensure ''pql init'' (ensureGitHookShim) reliably plants all four shims. Confirm a fresh clone + ''pql init'' + core.hooksPath=.githooks yields the full lifecycle with a clean tree. Alternatively, if committed shims are deemed desirable for zero-init clones, commit all four and document why -- but that contradicts T-28/T-39, so it would need a D-18 amendment.

Surfaced 2026-06-05 while wiring core.hooksPath on the pql repo: pre-commit/post-merge were absent from the active hook set until ''pql init'' planted them.

Resolved 2026-06-05. No code change needed: pql init''s ensureGitHookShim already plants all four shims into the resolved core.hooksPath dir. Fix was repo-state alignment: git rm --cached .githooks/post-checkout and post-rewrite, extended the .gitignore stanza to ignore all four replication shims (rationale: a non-pql contributor must be able to use the repo without pql hook machinery in their tree), and documented the set-hooksPath-before-init ordering in CLAUDE.md. pre-push stays tracked (project CI gate, not a pql shim). Verified end-to-end on a fresh clone: only pre-push tracked; after core.hooksPath=.githooks + pql init all four shims plant with a clean tree and the hooks fire. Committed in adf44e3.', 'in_progress', 'medium', NULL, NULL, 'D-18', '2026-06-05 10:44:32', '2026-06-05 11:15:00', NULL, 'c6ca6c6dcf2185375f4e4c7db3beb572', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-52', 'task', NULL, 'Unify .githooks shim tracking: post-checkout/post-rewrite still tracked, pre-commit/post-merge ignored', 'The four pql replication hook shims in .githooks/ are tracked inconsistently:

  - .githooks/post-checkout  -> TRACKED (git ls-files)
  - .githooks/post-rewrite   -> TRACKED
  - .githooks/pre-commit     -> gitignored (.gitignore L65)
  - .githooks/post-merge     -> gitignored (.gitignore L66)

All four are functionally identical static two-line shims (git rev-parse + source .pql/hooks/<name>); none bakes a per-developer path (that lives in the .pql/hooks/* bodies, correctly ignored under .pql/*). So the split is unintended drift, not a real distinction. (pre-push is legitimately tracked -- it is the hand-authored lint gate, not a replication shim.)

History: T-28/T-38/T-39 settled that hook scripts + shims are per-clone, planted by ''pql init'', not tracked; T-39 git-rm''d .pql/hooks/ and dropped the !.pql/hooks/ exception. T-30 (cancelled) records that ensureGitHookShim is supposed to plant ALL FOUR .githooks/ shims and that post-checkout/post-rewrite were the ones being missed. The tracked post-checkout/post-rewrite shims are the leftover that escaped the T-39 cleanup, and .gitignore lacks matching ignore rules for them.

Impact: latent. A fresh clone that only runs ''git config core.hooksPath .githooks'' (without ''pql init'') gets pre-push + the two tracked rebuild shims, but NOT pre-commit/post-merge -- so write-through staging and post-merge import silently don''t fire until init runs. The asymmetry also makes the per-clone-hooks invariant (T-28) ambiguous.

Proposed resolution (align to the settled per-clone policy): git rm .githooks/post-checkout and .githooks/post-rewrite, add them to the .gitignore stanza alongside pre-commit/post-merge, and ensure ''pql init'' (ensureGitHookShim) reliably plants all four shims. Confirm a fresh clone + ''pql init'' + core.hooksPath=.githooks yields the full lifecycle with a clean tree. Alternatively, if committed shims are deemed desirable for zero-init clones, commit all four and document why -- but that contradicts T-28/T-39, so it would need a D-18 amendment.

Surfaced 2026-06-05 while wiring core.hooksPath on the pql repo: pre-commit/post-merge were absent from the active hook set until ''pql init'' planted them.

Resolved 2026-06-05. No code change needed: pql init''s ensureGitHookShim already plants all four shims into the resolved core.hooksPath dir. Fix was repo-state alignment: git rm --cached .githooks/post-checkout and post-rewrite, extended the .gitignore stanza to ignore all four replication shims (rationale: a non-pql contributor must be able to use the repo without pql hook machinery in their tree), and documented the set-hooksPath-before-init ordering in CLAUDE.md. pre-push stays tracked (project CI gate, not a pql shim). Verified end-to-end on a fresh clone: only pre-push tracked; after core.hooksPath=.githooks + pql init all four shims plant with a clean tree and the hooks fire. Committed in adf44e3.', 'done', 'medium', NULL, NULL, 'D-18', '2026-06-05 10:44:32', '2026-06-05 11:15:00', NULL, '09a7d21d284cd6bbba8228577161b956', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-53', 'task', NULL, 'Don''t narrate changelog-dirty after ticket mutations', 'A `pql ticket` change (create / status transition) leaves `.pql/changelog/` dirty; the auto-commit hook persists it on the next `git commit`. This is known and expected behavior — the pre-commit hook stages `.pql/changelog/` so it lands in the same commit as the change that produced it.

Don''t narrate "the ticket won''t persist until committed" on every ticket edit. Either quietly fold the bookkeeping into a commit or trust the normal commit flow.', 'backlog', 'medium', NULL, NULL, NULL, '2026-06-06 08:48:11', '2026-06-06 08:48:11', NULL, '31c949c539ed381225e4c87dc5ec9bf1', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-53', 'task', NULL, 'Don''t narrate changelog-dirty after ticket mutations', 'A `pql ticket` change (create / status transition) leaves `.pql/changelog/` dirty; the auto-commit hook persists it on the next `git commit`. This is known and expected behavior — the pre-commit hook stages `.pql/changelog/` so it lands in the same commit as the change that produced it.

Don''t narrate "the ticket won''t persist until committed" on every ticket edit. Either quietly fold the bookkeeping into a commit or trust the normal commit flow.', 'done', 'medium', NULL, NULL, NULL, '2026-06-06 08:48:11', '2026-06-06 08:48:16', NULL, 'c5b9117bb4006a022fb4a442abf372d1', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-54', 'task', NULL, 'Surface ticket-ID collisions loudly at changelog replay', 'Ticket IDs are allocated as max(existing)+1 against the *local* changelog, so two clones/branches/sessions that file between syncs can both pick the same T-NNN. This is an accepted cost of sequential IDs with no central authority (git provisions none) — we don''t want to prevent it.

The real hazard is that it''s currently *silent*: `tickets` replays with `ON CONFLICT(id) DO UPDATE`, so two unrelated tickets claiming one id merge into a single row (higher updated_at/hash wins) with no error. The corruption is invisible until someone notices a wrong title.

Make it loud instead of preventing it: at changelog replay / `pql plan rebuild`, detect when one `id` is claimed by two distinct `hash` lineages (different created_at/title for the same id) and surface it as a diagnostic rather than letting the upsert paper over it. Keeps sequential human-readable IDs; turns invisible merge into a rebuild-time warning the maintainer can reconcile by re-filing one under a fresh id.

Context: hit live on 2026-06-06 — local T-52 collided with an already-pushed remote T-52, resolved by re-filing as T-53.', 'backlog', 'medium', NULL, NULL, NULL, '2026-06-06 08:53:46', '2026-06-06 08:53:46', NULL, '17d9e77f443a6fe26e19d075873a5031', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-54', 'task', NULL, 'Surface ticket-ID collisions loudly at changelog replay', 'Ticket IDs are allocated as max(existing)+1 against the *local* changelog, so two clones/branches/sessions that file between syncs can both pick the same T-NNN. This is an accepted cost of sequential IDs with no central authority (git provisions none) — we don''t want to prevent it.

The real hazard is that it''s currently *silent*: `tickets` replays with `ON CONFLICT(id) DO UPDATE`, so two unrelated tickets claiming one id merge into a single row (higher updated_at/hash wins) with no error. The corruption is invisible until someone notices a wrong title.

Make it loud instead of preventing it: at changelog replay / `pql plan rebuild`, detect when one `id` is claimed by two distinct `hash` lineages (different created_at/title for the same id) and surface it as a diagnostic rather than letting the upsert paper over it. Keeps sequential human-readable IDs; turns invisible merge into a rebuild-time warning the maintainer can reconcile by re-filing one under a fresh id.

Context: hit live on 2026-06-06 — local T-52 collided with an already-pushed remote T-52, resolved by re-filing as T-53.', 'ready', 'medium', NULL, NULL, NULL, '2026-06-06 08:53:46', '2026-06-08 14:38:13', NULL, 'ca497e5d6a9f73eec9afe8f50135c112', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-45', 'task', NULL, 'implement or formally defer documented DSL grammar surface', 'docs/pql-grammar.md documents operators/functions that are not implemented, so documented examples error at runtime (surfaced by the 2026-05-31 docs-vs-code audit): (1) REGEXP — parser emits it but no UDF is registered (only ''reverse'' in internal/store/udf.go), so ''name REGEXP ...'' fails with ''no such function'' (exit 70); (2) functions contains/position/slice/dirname/basename/extension/now()/today() and cast(x AS type) are absent from functionMap (internal/query/dsl/eval/compile.go) and CAST has no parse rule; (3) array columns inside length()/array fns error with bare_array_ref. Either implement these (register REGEXP UDF, add the functions + a CAST parse rule, allow array fns in projections) or keep them deferred. Interim: docs/pql-grammar.md has been marked ''planned'' for the unimplemented parts; this ticket tracks closing the gap for real.', 'ready', 'medium', NULL, NULL, NULL, '2026-05-31 12:25:23', '2026-06-08 14:39:01', NULL, '41b4815faf1fac43af2e121e1485d148', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-54', 'task', NULL, 'Surface ticket-ID collisions loudly at changelog replay', 'Ticket IDs are allocated as max(existing)+1 against the *local* changelog, so two clones/branches/sessions that file between syncs can both pick the same T-NNN. This is an accepted cost of sequential IDs with no central authority (git provisions none) — we don''t want to prevent it.

The real hazard is that it''s currently *silent*: `tickets` replays with `ON CONFLICT(id) DO UPDATE`, so two unrelated tickets claiming one id merge into a single row (higher updated_at/hash wins) with no error. The corruption is invisible until someone notices a wrong title.

Make it loud instead of preventing it: at changelog replay / `pql plan rebuild`, detect when one `id` is claimed by two distinct `hash` lineages (different created_at/title for the same id) and surface it as a diagnostic rather than letting the upsert paper over it. Keeps sequential human-readable IDs; turns invisible merge into a rebuild-time warning the maintainer can reconcile by re-filing one under a fresh id.

Context: hit live on 2026-06-06 — local T-52 collided with an already-pushed remote T-52, resolved by re-filing as T-53.', 'in_progress', 'medium', NULL, NULL, NULL, '2026-06-06 08:53:46', '2026-06-08 15:03:00', NULL, '88cae52c586b9ad4833810d51660aad1', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-54', 'task', NULL, 'Surface ticket-ID collisions loudly at changelog replay', 'Ticket IDs are allocated as max(existing)+1 against the *local* changelog, so two clones/branches/sessions that file between syncs can both pick the same T-NNN. This is an accepted cost of sequential IDs with no central authority (git provisions none) — we don''t want to prevent it.

The real hazard is that it''s currently *silent*: `tickets` replays with `ON CONFLICT(id) DO UPDATE`, so two unrelated tickets claiming one id merge into a single row (higher updated_at/hash wins) with no error. The corruption is invisible until someone notices a wrong title.

Make it loud instead of preventing it: at changelog replay / `pql plan rebuild`, detect when one `id` is claimed by two distinct `hash` lineages (different created_at/title for the same id) and surface it as a diagnostic rather than letting the upsert paper over it. Keeps sequential human-readable IDs; turns invisible merge into a rebuild-time warning the maintainer can reconcile by re-filing one under a fresh id.

Context: hit live on 2026-06-06 — local T-52 collided with an already-pushed remote T-52, resolved by re-filing as T-53.', 'review', 'medium', NULL, NULL, NULL, '2026-06-06 08:53:46', '2026-06-08 15:24:42', NULL, '99f4a8281f8ca0c585c142500267a01e', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (id, type, parent_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('T-45', 'task', NULL, 'implement or formally defer documented DSL grammar surface', 'docs/pql-grammar.md documents operators/functions that are not implemented, so documented examples error at runtime (surfaced by the 2026-05-31 docs-vs-code audit): (1) REGEXP — parser emits it but no UDF is registered (only ''reverse'' in internal/store/udf.go), so ''name REGEXP ...'' fails with ''no such function'' (exit 70); (2) functions contains/position/slice/dirname/basename/extension/now()/today() and cast(x AS type) are absent from functionMap (internal/query/dsl/eval/compile.go) and CAST has no parse rule; (3) array columns inside length()/array fns error with bare_array_ref. Either implement these (register REGEXP UDF, add the functions + a CAST parse rule, allow array fns in projections) or keep them deferred. Interim: docs/pql-grammar.md has been marked ''planned'' for the unimplemented parts; this ticket tracks closing the gap for real.', 'backlog', 'medium', NULL, NULL, NULL, '2026-05-31 12:25:23', '2026-06-08 15:40:16', NULL, '22158b2a9bfd4f179889fed8af3fe166', 1) ON CONFLICT(id) DO UPDATE SET type=excluded.type, parent_id=excluded.parent_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
