INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXNRA8H27DMXJ73K9G', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'add canonical row columns and content hash to all planning tables', 'Forward migration on every planning table to add three columns: created_at (timestamp, set on INSERT), updated_at (timestamp, set on every write — used as the LWW key and the changelog month-bucketing key), and hash (TEXT, set to H(canonical(row except hash))). Plus a canonical_version column or schema-level marker so canonicalisation rule changes are detectable.

Implement canonical row serialisation in internal/planning/ — a fixed column-order projection with strict value formatting (NULL sentinel, integer vs float distinction, timestamp ISO format). Compute hash at write-finalisation in repo helpers (internal/planning/repo/*.go) on every INSERT/UPDATE so the column is always current.

Inline LWW guard for upserts is the SQL idiom: WHERE excluded.updated_at > target.updated_at OR (excluded.updated_at = target.updated_at AND excluded.hash > target.hash). Codify it in a helper used by both writers (D-16) and exporters (T-19).

Touches: internal/planning/schema.go (forward migration), internal/planning/repo/*.go (write paths), new internal/planning/canonical.go (canonicalisation + hash function). Tests: round-trip determinism (two replicas hash identical content to identical bytes), canonical_version bump triggers re-hash, NULL/edge-value coverage.', 'done', 'high', 'claude', NULL, 'D-16', '2026-05-08 07:46:29', '2026-05-08 10:55:14', NULL, '1702798ad0a0d847376ef6e2b4ecd4a1', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY02BSZ65DRJJCR660', 'story', NULL, 'ship clean-house skill v1.0 as pql sub-skill', 'Add a clean-house skill to the pql installer that runs documentation-discipline passes over a DQR (Decisions / Questions / Rejected) markdown system. Claude is the runtime (no external script); the skill walks decisions/, runs the rule catalog, batches findings via AskUserQuestion, and applies fixes via pql queries + Edit. Pql remains a dumb data layer — gets new queries only when the skill names one.', 'done', 'medium', 'claude', NULL, NULL, '2026-05-06 12:38:49', '2026-05-08 10:55:14', NULL, '1fe8ffd9e0b968b0cc9e8427b2f7dae0', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWVFB2NHGW9KR5YFWM', 'task', NULL, 'tighten clean-house rules.md (catalog fixes)', 'Three changes to internal/skill/clean-house/references/rules.md, surfaced by the first end-to-end clean-house run:\n\n1. RULE-ANCHOR-DRIFT detection rewrite. Current logic checks anchor links against the referenced record''s body headings (from pql decisions read), but anchor-only links resolve against the file''s full heading set — including record-level ''### D-N: …'' headings stripped from the body. Replace detection with: read the source body''s *file* (decisions/<file>), extract every ATX heading, build a file-level slug index, check anchor-only links against that. Cross-file anchors (path.md#slug) check the path''s slug index.\n\n2. RULE-DEAD-FILE-REFERENCE filtering. Detection produced 6/6 false positives this run: placeholder tokens (tickets/T-NNN.md, sessions/.../brief.md), package-relative refs (repo/tickets.go for the real internal/planning/repo/tickets.go), sibling-relative refs (questions.md from a body in decisions/, resolved against repo root). Add to detection: skip tokens containing ''T-NNN'', ''...'', ''<'', ''>''; resolve relative paths against the source file''s directory before os.Stat; fallback to basename-match across the repo (find -name) before flagging.\n\n3. Per-rule Finding ID format. Each rule entry needs a ''Finding ID:'' field so the skip ledger can re-recognize the same finding across runs (precondition for the 3-strikes promote-prompt logic). Examples: RULE-ANCHOR-DRIFT → ''<source-record>:<target-slug>''; RULE-SUNSET-WITHOUT-TICKET → ''<record-id>:<phrase-hash-8>''; RULE-FILE-OVER-THRESHOLD → ''<file-path>''.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 14:35:25', '2026-05-08 10:55:14', NULL, '37ee19edfc73b20a1c0b7e9be3443d54', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXKXZ9DTS740JG5398', 'task', '06FB0TGPVYTA9JDX9MHSS762SM', 'align decisions show with the join-tree helper pattern', 'Audit internal/cli/decisions.go (decisions show with --with-refs / --with-tickets) for a parallel ad-hoc tree shape. If found, factor into a buildDecisionTree helper analogous to buildShowTree so decision rendering stays consistent across decisions show, decisions read, and any future surface (e.g. plan status drilldowns).', 'done', 'medium', 'claude', NULL, NULL, '2026-05-06 10:07:05', '2026-05-08 10:55:14', NULL, '453d2ff4abb8e7aa29c23304170968bf', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVYPF23S0EK93RV7EPW', 'bug', NULL, 'pre-commit hook misses bootstrap snapshot when pql-plan.json is untracked', 'internal/cli/init.go:374 pqlPreCommitHook gates ''git add'' on ''git diff --quiet -- .pql/pql-plan.json''. For an untracked file, git diff returns 0 (no diff) so the negation is false and the file is never staged. Result: the first commit after ''pql init'' silently fails to commit the planning snapshot. Reproducer: fresh repo, pql init, pql ticket new ..., git commit -m ''...'' — pql-plan.json stays untracked. Fix: also stage when the file exists but is untracked, e.g. test ''git ls-files --error-unmatch ... 2>/dev/null'' or unconditionally ''git add -f .pql/pql-plan.json'' if the file exists. Update both the embedded hook script and any tests asserting hook behaviour.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 10:11:03', '2026-05-08 10:55:14', NULL, '4b93999705714c7e6fbf3db85eb75087', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVW61HBX6FXPJJ6PJR8', 'task', '06FB0TGPVY02BSZ65DRJJCR660', 'expose decision body heading anchors on pql decisions read', 'Add a ''headings: [{level, text, slug}]'' array to the JSON returned by ''pql decisions read <id>''. The slug must follow the same convention used by markdown anchor links in the source (typically lowercase-hyphen — match the project''s existing slugger; check whether one already lives in internal/index/parser/markdown for headings used elsewhere). Required for clean-house RULE-ANCHOR-DRIFT detection — without it, the skill cannot resolve cross-reference link targets to existing headings without re-parsing the body.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 12:42:06', '2026-05-08 10:55:14', NULL, '7cfea197f945e0e8fcff54ea6f94a56d', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZ26WZJJQS200J4GB4', 'task', '06FB0TGPVY02BSZ65DRJJCR660', 'extend skill installer to ship clean-house as sub-skill', 'Refactor internal/skill/ so the installer can ship multiple skills. Today it embeds one SKILL.md from internal/skill/SKILL.md and writes to .claude/skills/pql/SKILL.md. Need to also embed internal/skill/clean-house/{SKILL.md,references/rules.md} and write to .claude/skills/clean-house/. The install lockfile (.pql-install.json) extends to track both skills'' state. Updates: pql skill install, pql skill status, pql doctor, pql init''s --with-skill flag (if relevant). Tests: skill install creates both directories; --force refreshes both; status correctly reports each independently.', 'done', 'medium', 'claude', NULL, NULL, '2026-05-06 12:42:06', '2026-05-08 10:55:14', NULL, '83ad4b5391ea351dc81d22c8a31994e9', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWA8XFR7TR7EBY5G90', 'task', NULL, 'Track conditions for D-1 revisit', 'D-1 commits to no vector retrieval but documents two AND-conditions for revisiting: (a) a specific class of agent task is shown, with examples, to fail on structured retrieval and succeed on semantic; AND (b) a pure-Go embedded vector store reaches tier-one quality. Either alone is insufficient. This ticket exists to surface the revisit gate in plan whatsnext / plan board so the trigger doesn''t get forgotten if/when the conditions arrive. No work to do until both fire — the ticket stays in backlog as a sentinel.', 'backlog', 'low', NULL, NULL, 'D-1', '2026-05-06 14:00:50', '2026-05-08 10:55:14', NULL, 'a0a701d46dc6ca34065c3e4a24bd2d5f', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZRJQRF2G2ENV0JQNC', 'task', NULL, 'auto-resolve skill scope: user-scope wins when present', 'pql skill install (no --user flag) should auto-resolve which scope to operate on:

  - If ANY bundled skill is already installed at user-scope (~/.claude/skills/<name>/), treat user-scope as canonical for the whole suite. Install/update every bundled skill there. Do not touch project-scope.

  - If no user-scope install exists, install at project-scope (current behavior).

  - --user flag still forces user-scope unconditionally — only way to make the *initial* user-scope install.

When auto-resolving to user-scope, also tidy up any safely-removable project-scope install (state in {current, stale, missing}). Preserve project-scope if state is modified or unknown — the user has hand-edits, do not nuke them; surface a note instead.

This same resolution applies to:
  - pql skill status (no flag) — report effective scope
  - pql init skill step — install/update at the resolved scope
  - pql skill uninstall (no flag) — operate on project-scope only (do not surprise users by removing user-scope without --user). Note when user-scope exists.

pql doctor should report BOTH scopes so drift between them stays visible.

Add a Scope field on the per-skill JSON output (user | project) so callers can tell which install they are looking at.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 13:36:08', '2026-05-08 10:55:14', NULL, 'b0774cd764190fc44fbe3cce9bad8d49', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVYTA9JDX9MHSS762SM', 'story', NULL, 'unify show-tree rendering across ticket and decision surfaces', 'Audit which surfaces build a ticket/decision join-tree (ancestors, decisions, blockers, children) and route them all through buildShowTree (introduced in v1.4.5 in internal/cli/ticket.go). Currently used by ticket show, ticket refine next, ticket refine write. Plan whatsnext / plan review use the older whatNextResult shape; decisions show may have a parallel pattern. Goal: one canonical helper, identical JSON output where the data overlaps, single place to tweak rendering.', 'done', 'medium', 'claude', NULL, NULL, '2026-05-06 10:07:05', '2026-05-08 10:55:14', NULL, 'ba5d53eeac6efe8a36fd6e7405620459', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWTP205NJ9Y9QWFH34', 'task', '06FB0TGPVYTA9JDX9MHSS762SM', 'route plan whatsnext and plan review through buildShowTree', 'Replace whatNextResult in internal/cli/plan.go with the ticketShowTree shape (or refactor whatNextResult to embed it). enrichTicket already returns the same ancestors/children/decisions data — collapse the two so plan whatsnext, plan review, ticket show, and ticket refine emit identical join-tree JSON for the same ticket. Keep the Message field for the no-actionable-tickets case.', 'done', 'medium', 'claude', NULL, NULL, '2026-05-06 10:07:05', '2026-05-08 10:55:14', NULL, 'df7cda66b1351b98bc738f2199d03911', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZ2QX97W6P0VTGH6YM', 'bug', NULL, 'pql init writes hooks to .git/hooks/ even when core.hooksPath is redirected', 'When git''s core.hooksPath config points at a custom directory (this repo uses ''.githooks/'' for its pre-push gate), git ignores .git/hooks/ entirely — so the pql shim ensureGitHookShim writes there is never invoked, and the .pql/hooks/{pre-commit,post-merge} scripts never fire from git commit / git pull. Witnessed locally: the show-tree unification commit (T-2) didn''t auto-stage .pql/pql-plan.json even though pql plan export --stage works correctly when run by hand.

Reproducer: ''git config core.hooksPath .githooks'' in any pql-init''d repo. Commits stop carrying the snapshot.

Fix: ensureGitHookShim in internal/cli/init.go should resolve the effective hooks path. Two strategies:
  1. Read ''git config --get core.hooksPath'' (or the equivalent env var GIT_HOOKS_PATH) and write the shim there. If the directory doesn''t exist or isn''t writable, surface a clear note in the init JSON output rather than silently planting a dead shim.
  2. Append to an existing pre-commit/post-merge shim in that directory rather than overwriting (so the project''s own hook keeps working alongside pql''s).

Test: assert ensurePlanExportHook with a pre-set core.hooksPath writes into the redirected dir, not .git/hooks/.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 12:08:36', '2026-05-08 10:55:14', NULL, 'e453135f5989ee91de14cee1c72cefa8', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXH87HGN7F00THXND8', 'task', NULL, 'tighten clean-house SKILL.md (procedure + state)', 'Five changes to internal/skill/clean-house/SKILL.md, surfaced by the first end-to-end clean-house run:\n\n1. Add step 1.5 ''Probe conventions''. Read decisions/.clean-house.yaml if present; otherwise infer from the project: heading depth (## vs ###), backlink phrasing (Resolves: vs other), staleness threshold (default 60). Rules.md entries should consume these probed values instead of hardcoding. Also documents the .clean-house.yaml shape so projects can pin conventions explicitly.\n\n2. In step 4 ''Walk decisions/'', filter records whose file_path begins with ''legacy/''. The ''What this skill does NOT do'' bullet promises this but the procedure doesn''t enforce it.\n\n3. In step 6, define ''stop asking'' globally: exits all remaining prompts in the run (mechanical batches and judgment findings alike); everything pending lands in the skip ledger as deferred; summary still emitted.\n\n4. In step 7, define the ''show diff first'' loop: print unified diff of the staged edits, then re-prompt with the same options minus ''show diff first'' so the user can''t loop forever.\n\n5. Define the promotion-candidate history file. Output template promises ''RULE-X (5/7 runs)'' but no storage is named. Either repurpose the skip ledger with per-run section headers (timestamped, plus ''fired'' / ''skipped'' counts per rule) or add a sibling .clean-house-history.md. Pick one; document the shape.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 14:35:25', '2026-05-08 10:55:14', NULL, 'e68e1ff75dc41de0776edaffe6bce1b7', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY30RVGVQMHMV0Q1Q8', 'task', '06FB0TGPVY02BSZ65DRJJCR660', 'draft clean-house SKILL.md + references/rules.md', 'Create internal/skill/clean-house/{SKILL.md,references/rules.md}. SKILL.md is the v1.0 integrated form (Claude as runtime; no Python stopgap framing). references/rules.md contains 6-8 starter rules with explicit Detection sections that name the pql query / file primitive each needs — that detection list reveals the pql gaps for follow-up tickets.', 'done', 'medium', 'claude', NULL, NULL, '2026-05-06 12:38:49', '2026-05-08 10:55:14', NULL, 'e69c3a29f8f46dacfa200f12171ff406', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVYV1433X2CBE8PK9BC', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'implement soft deletes via deleted_at column', 'Forward migration adding deleted_at (timestamp, NULL = live) to every planning table. Route every existing DELETE through UPDATE ... SET deleted_at = ?. Update every read query in internal/planning/repo/*.go to filter WHERE deleted_at IS NULL by default; add an --include-deleted flag where the surface needs visibility into stubs (e.g. audit, recovery).

Stubs persist in pql.db and the changelog so other replicas know the deletion is intentional rather than missing — without this, replay against a fresh replica would re-INSERT the row. The changelog upsert for a deletion is just a regular line where deleted_at is non-null.

Touches: internal/planning/schema.go (migration), internal/planning/repo/*.go (every read query gains the filter; every delete becomes a soft-delete UPDATE), audit log entries for deletion events (recorded as today). Tests: round-trip soft delete / undelete, replay convergence (replica A deletes, replica B has never seen the row → replay creates the stub, then deletion replays into the stub).

Stub purge / retention is deferred to Q-10. This ticket lands the column and the read-path filter; it does not implement purge.', 'done', 'high', 'claude', NULL, 'D-17', '2026-05-08 07:46:41', '2026-05-08 10:55:14', NULL, 'f22460f34cf77785cc11825db466eaaa', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZP1WF9MGH86K812X4', 'task', NULL, 'harden plan export hook: --stage flag + absolute pql path', 'Two related issues with the pre-commit hook installed by pql init:

1. Staging logic lives in shell, not pql. Move it into ''pql plan export --stage'' so pql owns the git-add edge cases (untracked / gitignored / dirty). Bare ''pql plan export'' stays side-effect-free; --stage opts in. Update internal/cli/init.go''s pqlPreCommitHook to call ''pql plan export --stage'' (one line, no [ -f ] test).

2. Hook silently no-ops when pql isn''t on PATH for git''s hook shell (witnessed locally — git commit -m ''...'' didn''t fire the hook even though pql was on the user''s interactive PATH). Fix: at pql init time, resolve os.Executable() and bake the absolute path into the generated hook script instead of ''pql''. Drop the ''command -v pql'' guard since the absolute path either exists or it doesn''t.

Touches: internal/cli/init.go (hook content), internal/cli/plan.go (export verb adds --stage flag and stage helper). Requires a new repo-level helper or direct git shell-out for the staging step. Add tests: hook-content assertion that the resolved path is baked in; cli test for ''plan export --stage'' both when file is untracked and when it''s already tracked.', 'done', 'high', 'claude', NULL, NULL, '2026-05-06 10:14:20', '2026-05-08 10:55:14', NULL, 'f9c4d092834ac001e76326064d72e6af', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX4BTSWH5RM3QNFTRC', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'update pql init to install hooks, schema files, and gitattributes for replication', 'Extend internal/cli/init.go to wire the full replication lifecycle on a fresh clone or an upgraded repo:

1. Create .pql/changelog/ and per-table subdirectories (.pql/changelog/tickets/, .pql/changelog/audit_log/, .pql/changelog/refs/, etc. — every planning table that participates in replication).
2. Write 0000-schema.sql into each <table>/ directory containing the CREATE TABLE IF NOT EXISTS statement for that table. The migration runner (D-6) generates these from its current schema knowledge — reuse rather than duplicate.
3. Install four hooks (resolved absolute pql path, per the T-5 fix):
   - pre-commit: pql plan export --stage (existing path; just confirm the verb still does the right thing under the new exporter).
   - post-merge: pql plan import (silent if quick; default behaviour).
   - post-checkout: if [ "" = "1" ]; then echo ''rebuilding pql database...''; pql plan rebuild; fi
   - post-rewrite: echo ''rebuilding pql database after rewrite...''; pql plan rebuild
4. Write or amend .gitattributes with the line: .pql/changelog/*.sql merge=union
5. Stage all the above so the user''s first commit lands the new layout.

Touches: internal/cli/init.go (most of the work), reuses migration runner for schema generation, depends on T-19/T-20/T-21 verb behaviour. Tests: fresh-init produces all expected files; re-init is idempotent; .gitattributes append doesn''t duplicate the line if it''s already present.', 'done', 'high', NULL, NULL, 'D-18', '2026-05-08 07:47:34', '2026-05-08 10:56:55', NULL, '6761f151aa28aeff6f89afa84e6458e3', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWTXX2BQ8YEDM7DVVR', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'migrate legacy pql-plan.json into the changelog on first export', 'Existing repos have committed pql-plan.json artifacts (per D-13, now superseded). On first pql plan export against an upgraded repo, detect the legacy file and convert it transparently:

1. Detect: .pql/changelog/ does not exist OR is empty AND pql-plan.json exists at the vault root.
2. Run pql plan import --legacy <pql-plan.json> to populate pql.db from the JSON snapshot (the existing import path is the migration tool).
3. Run pql plan export under the new format — this writes 0000-schema.sql and the initial data files into .pql/changelog/<table>/.
4. git rm pql-plan.json so the legacy artifact doesn''t linger.
5. Stage the new changelog directory, the schema files, and the deletion of pql-plan.json — all part of the same pre-commit hook invocation.
6. Stdout: clear migration message so the user knows what happened in the next commit.

The legacy import path needs a flag (--legacy) so it doesn''t conflict with the new replay-from-changelog import. After this migration commit lands, all future operations use the new format.

Touches: internal/cli/plan.go (legacy detection in export, --legacy flag on import), internal/cli/init.go (probably also runs the migration when init is run on an existing legacy repo). Tests: clide vault as the target — clone, run upgraded pql, observe transparent migration commit; verify subsequent flows use the new format.', 'done', 'high', NULL, NULL, 'D-15', '2026-05-08 07:47:46', '2026-05-08 11:00:15', NULL, 'e041444b9ae7421b1436db3468143660', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWVQNGBJPQVZ3C0BAM', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'integrate schema migrations with numbered changelog schema files', 'Adapt the in-house migration runner (D-6) so schema migrations land in the changelog directories as numbered files rather than (or in addition to) inline Go SQL.

Naming convention: <NNNN>-schema-<slug>.sql in each .pql/changelog/<table>/. Lexicographic sort puts these before <YYYY-MM>.sql data files automatically. Each file is idempotent (CREATE TABLE IF NOT EXISTS, ALTER TABLE ... ADD COLUMN guarded by introspection or a try-catch in pure SQLite, etc.).

Migration runner changes (internal/planning/schema.go):
- On migration: write the migration SQL to <next-N>-schema-<slug>.sql in each affected table directory, then apply it locally via the existing transaction-wrapped runner. Update schema_migrations table.
- On import: schema files are part of the lexicographic replay — they apply via CREATE TABLE IF NOT EXISTS / ALTER TABLE patterns and the schema_migrations table tracks what''s been applied. Replicas pulling new schema files apply them on next import.
- Include canonical_version metadata in the schema files so canonicalisation rule changes (per T-17) are visible alongside structural migrations.

This keeps D-6''s runner architecture (transactional, forward-only, in-house) but moves the migration artefact into the committed changelog so it travels with data and is replayable by any SQLite tool.

Touches: internal/planning/schema.go (migration emission + replay path), schema_migrations table interaction, internal/cli/init.go (T-22 generates the initial 0000-schema.sql via this same path). Tests: migration writes the file and applies it; replica pulls the file and applies via replay; conflicting concurrent migrations on different replicas converge cleanly.', 'done', 'medium', NULL, NULL, 'D-15', '2026-05-08 07:48:00', '2026-05-08 11:01:30', NULL, '780a74601dd98c38a15347cf9521446c', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZ435T95HN2HHJKZVM', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'implement pql plan rebuild for branch-switch and rebase recovery', 'New subcommand pql plan rebuild — drops planning tables and replays the full changelog from scratch. Used by post-checkout (branch switch) and post-rewrite (rebase) hooks because LWW-guarded incremental replay can only INSERT/UPDATE — it can''t remove rows that exist on the previous branch but not the new one.

Rebuild pipeline (internal/cli/plan.go):
1. DELETE FROM each planning table (or DROP and rely on schema files to recreate — simpler).
2. Reset last_import_marker, last_export_marker.
3. Run the import flow from T-20 against the entire changelog.
4. Stdout: summary (tables rebuilt, rows replayed, time taken).
5. Stderr: progress diagnostics for hook visibility.

Surface as a first-class command, not just a hook callee — power users may invoke it for disaster recovery or after manual changelog edits. Document under ''Plan subcommands'' in the skill.

Touches: internal/cli/plan.go (new rebuild verb), reuses the importer from T-20. Tests: rebuild-from-empty, rebuild-after-branch-with-deleted-rows (must not leak previous branch state), idempotent re-rebuild.', 'done', 'high', NULL, NULL, 'D-18', '2026-05-08 07:47:16', '2026-05-08 17:17:21', NULL, '3b5bfe825aebc71b25205ea78f97f8c0', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX0T46X2ZKR07MHZSW', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'rewrite pql plan export to emit per-table monthly changelog files', 'Replace the current JSON snapshot export (writes pql-plan.json) with the changelog format: emit SQL upsert lines into .pql/changelog/<table>/<YYYY-MM>.sql, one file per (table, month) combination based on the row''s updated_at.

Export pipeline (internal/cli/plan.go + new internal/planning/changelog/):
1. Read last_export_marker from pql.db meta table (local-only, gitignored side of state).
2. SELECT * FROM <table> WHERE updated_at > last_export_marker, ordered by (updated_at, hash). Two-pass: emit rows whose updated_at falls in the previous month into <prev-month>.sql, then current month into <current-month>.sql. Late-arriving rows for older months are rare but possible after clock corrections / backdated imports — handle the bucket placement by row, not by export time.
3. Each emitted line is an INSERT ... ON CONFLICT(<pk>) DO UPDATE SET ... WHERE excluded.updated_at > target.updated_at OR (excluded.updated_at = target.updated_at AND excluded.hash > target.hash). Use the canonical-projection helper from T-17 so the SQL line is byte-stable across replicas.
4. Append (don''t rewrite — files are append-only by month).
5. Advance last_export_marker after successful write.

Stage written files via git add (the existing --stage flag pattern from T-5).

Touches: internal/cli/plan.go (export verb body), new internal/planning/changelog/exporter.go, internal/planning/repo/meta.go (marker storage). Tests: round-trip with T-20 import; same-millisecond rows get sorted deterministically by hash; previous-month bucket only touched when rows belong there.

Decisions still source from markdown, not changelog (D-8 preserved) — exporter skips the decisions table.', 'done', 'high', NULL, NULL, 'D-15', '2026-05-08 07:46:54', '2026-05-08 17:17:21', NULL, '7821d5da8881dc3cfd823f3634f182ed', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWZE5DDTGNDEA292G4', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'rewrite pql plan import to replay changelog directories', 'Replace JSON import with changelog replay. Walk .pql/changelog/<table>/ directories in lexicographic file order so 0000-schema.sql and other zero-prefixed schema files run before year-prefixed data files. Replay every line that hasn''t been seen since last_import_marker (tracked per-file via mtime or per-line via offset).

Import pipeline (internal/cli/plan.go + internal/planning/changelog/importer.go):
1. Read last_import_marker from pql.db meta.
2. For each .pql/changelog/<table>/ directory:
   a. Run files in lexicographic order, tracking position.
   b. Schema files apply via CREATE TABLE IF NOT EXISTS (idempotent).
   c. Data files: each line is an inline-guarded upsert; replay is idempotent because the WHERE clause from T-19 prevents stale lines from overwriting newer state.
3. Advance last_import_marker on success.

Idempotency is load-bearing: the same line replayed N times converges to the same result, regardless of starting state. This is the property that lets the hooks (D-18) be cheap and the import to fire from multiple paths (post-merge, pql plan rebuild) without coordination.

Touches: internal/cli/plan.go (import verb body), new internal/planning/changelog/importer.go, internal/planning/repo/meta.go. Tests: replay-twice convergence, replay-out-of-order convergence, schema_version mismatch handling (refuse and surface diagnostic), partial-replay resumption after interrupted run.', 'done', 'high', NULL, NULL, 'D-15', '2026-05-08 07:47:06', '2026-05-08 17:17:21', NULL, '943bac6734c6ef7edb11f024204c092c', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY0RRS3WNE1JD19R44', 'task', '06FB0TGPVWMBMBKQBGFSQKQ7KR', 'multi-machine integration test scenario with clide', 'Use the clide repo (postmeridiem/clide) as the integration test bed for the new replication flow. clide has the right shape: multi-machine, multi-branch, real concurrent edits, decisions sourced from markdown, custom git hooks integrating with pql''s hook chain — which is exactly what produced the original pql-plan.json merge conflict that motivated this work.

Test protocol:
1. Migration test: clone clide at HEAD (which still has pql-plan.json), run upgraded pql, observe the transparent migration from T-23 — pql-plan.json removed, .pql/changelog/ populated, audit log preserved.
2. Concurrent-commit test: two clones, each makes a different ticket transition (one closes a bug, the other opens a feature ticket). Both push. Second push should fast-forward without conflict because per-table monthly files diverge cleanly. Pull on the now-merged main shows both transitions in the consolidated pql.db.
3. Concurrent same-ticket test: two clones edit T-XX.status to different values. Both push. Second push pulls and consolidates; LWW resolves to the later (commit-time, hash) edit. No data loss, no manual conflict resolution.
4. Branch-switch test: switch between branches with diverged ticket state. Confirm the post-checkout hook fires the visible rebuild and pql.db reflects only the current branch''s state.
5. Decision-divergence test: edit a decisions/*.md on one machine, transition a ticket on another, both commit + push. Decisions section reflects the markdown edit (still markdown-sourced per D-8); ticket transition lands in the consolidated state.

clide accepts the rough edges from the original pql-plan.json conflict for one or two more rebase cycles in exchange for being the integration test bed. Do not patch clide with bridge remediations (no manual merge=union on the legacy file, no disabling the auto-export hook) — the friction is the signal that proves the new design is needed.

Touches: no pql code changes — this is the validation pass after T-17 through T-24 land. Outcome: a write-up of observed behaviour vs expected, plus any bug tickets the test scenario surfaces.', 'done', 'medium', NULL, NULL, 'D-15', '2026-05-08 07:48:19', '2026-05-09 23:37:32', NULL, 'f56befe7a6442a827ac02a6c9b025ffd', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWMBMBKQBGFSQKQ7KR', 'story', NULL, 'implement changelog-based replication for planning state', 'Umbrella story for the changelog-based replication design captured in D-15 (changelog layout), D-16 (inline LWW guards + hashing), D-17 (soft deletes), and D-18 (hook architecture). Replaces the single mutable pql-plan.json snapshot (D-13, superseded) with .pql/changelog/<table>/ directories of per-month SQL upsert files plus per-table schema files. Children cover the discrete implementation slices: schema/columns, soft deletes, export rewrite, import rewrite, rebuild, init updates, legacy migration, schema-migration generation, and the clide integration test scenario. The original design doc at pql-plan-replication.md is retired in favour of these records — delete or archive once children land.', 'done', 'high', NULL, NULL, 'D-15', '2026-05-08 07:46:15', '2026-05-09 23:37:37', NULL, '6278605eba3bf41457d92fcf43c4d1dc', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWRKVHCGE0GAM5Y2NG', 'task', NULL, 'pql init should auto-update .gitignore to un-ignore .pql/changelog/', 'Surfaced by T-25 round 2 against clide. Clide had a pre-existing /.pql/* + !/.pql/pql-plan.json + !/.pql/hooks/ ignore stanza. After pql init plants .pql/changelog/, git add .pql/changelog/ is rejected as ignored — manual .gitignore edit is the only way forward.\n\nThe convention is already there (clide has !/.pql/hooks/), so detecting a /.pql/* rule + missing !/.pql/changelog/ entry and appending the un-ignore line is the natural fix.\n\nTouches: internal/cli/init.go ensurePqlGitignore (or a sibling helper). The function already amends .gitignore for the legacy snapshot file; just extend the entry list with !.pql/changelog/.\n\nTests: gitignore that already has the line is left alone (idempotent); gitignore without the line gets it appended; no .gitignore at all is left untouched (don''t create one).', 'done', 'medium', NULL, NULL, NULL, '2026-05-09 23:38:33', '2026-05-09 23:42:27', NULL, '175324b89c0f8b6e864dc0258f83bdd3', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWNBQ47ZN9H237DVTW', 'task', NULL, 'improve verifySchema error message to distinguish legacy vs changelog recovery', 'Existing message: ''planning: %s.%s missing — pql.db is from an earlier schema; delete .pql/pql.db and run pql plan import to rebuild (or pql plan rebuild if changelog files are present)''.\n\nThis confused clideclaude during T-25 because clide was a legacy repo (no .pql/changelog/ yet); ''pql plan import'' replays an empty changelog, leaves pql.db empty. The correct recovery for a legacy repo is rm pql.db && pql init (autoImportPlan picks the legacy fallback automatically) OR rm pql.db && pql plan import --legacy .pql/pql-plan.json.\n\nProposed wording:\n\n  planning: <table>.<col> missing — pql.db is from an earlier schema.\n  Recovery:\n    • If .pql/changelog/ has data:        rm .pql/pql.db && pql plan rebuild\n    • If only .pql/pql-plan.json exists:  rm .pql/pql.db && pql init\n      (autoImportPlan handles the legacy path automatically)\n\nTouches: internal/planning/schema.go verifySchema. Trivial wording fix.', 'done', 'low', NULL, NULL, NULL, '2026-05-09 23:38:33', '2026-05-09 23:42:27', NULL, '47541a06360a0e3a51cb7764ca906b0f', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVYKC9MW17D26750RS0', 'bug', NULL, 'changelog importer doesn''t advance last_export_marker — every commit re-emits all rows', 'Surfaced by T-25 round 2 against clide. After autoImportPlan replays the changelog into a fresh pql.db, last_export_marker stays empty in the meta table. The next pql plan export sees no marker and re-emits every row whose updated_at is non-null — i.e. all of them — appending ~5KB of unchanged-content INSERT statements per commit even when no ticket actually moved.\n\nFix: changelog.Import (in internal/planning/changelog/importer.go) should also write last_export_marker after successful replay. The semantic is correct: rows present in the changelog are by definition already exported. Setting last_export_marker to whatever last_import_marker becomes (now) means subsequent pql plan export only emits rows that mutated AFTER the replay — which is what the user expects.\n\nReproducer: rm .pql/pql.db; pql init (replays changelog); pql plan export — observes ''rows_written'' equal to total row count even though nothing changed.\n\nUnbounded changelog growth across no-op commits is the user-visible symptom.', 'done', 'high', NULL, NULL, NULL, '2026-05-09 23:37:50', '2026-05-09 23:42:27', NULL, 'bc6b459af1782fb1e228b4bbd23c2b95', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXFNE4YYMQ2ZBV3ZKM', 'task', NULL, 'exempt stance-shaped decisions from coverage report', 'pql decisions coverage flags every confirmed D without a linked T. For pql itself, ~13 of 14 confirmed decisions are founding/architectural stances (D-2 ''intent-level surface'', D-4 ''consumer-agnostic core'', D-5 ''CLI-first, not MCP'', etc.) — they document commitments, not roadmap items. A T per stance is ceremony.\n\nProposal: introduce a frontmatter field on D records, e.g. ''coverage: stance'' (free-form values to grow later — ''roadmap'', ''sentinel'', ''stance'', default ''roadmap''). ''pql decisions coverage'' filters out non-roadmap by default; --include-stance shows the full set.\n\nTouches: internal/planning/parser/decisions.go (parse new field), internal/planning/repo/decisions.go (Decision struct), internal/cli/decisions.go (filter + flag in coverage subcommand), the existing decisions/*.md (annotate D-2 through D-14 as ''coverage: stance'' once the parser supports it). D-1 stays default (''roadmap'') because it has T-12 tracking its revisit gate.', 'done', 'low', NULL, NULL, NULL, '2026-05-06 15:04:02', '2026-05-11 06:34:56', NULL, '1e19aedd6f688c043539f4723c46fab1', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY3RJA31D8CT8Z7J3M', 'bug', NULL, 'pql init bakes per-machine absolute pql path into hooks (shared-team footgun)', 'Surfaced by T-25 round 2 against clide. Hook bodies installed by pql init contain the absolute path of the pql binary that ran init, e.g. ''/var/home/alice/.local/bin/pql'' plan export --stage. clide tracks .pql/hooks/* in git per its !/.pql/hooks/ convention. Each developer''s pql init produces a permanent dirty diff against the tracked content because their absolute path differs.\n\nclideclaude worked around by replacing the abs paths with bare ''pql'' (PATH-based) on commit. That works for them but regresses T-5''s fix, which baked the abs path because git''s hook shell PATH is not the user''s interactive PATH and the hooks would silently no-op.\n\nDesign tension: T-5''s fix was correct for single-user setups and broken for shared-clone setups. Two reconciliation paths:\n  a) Don''t track .pql/hooks/ in git — let each developer''s pql init plant locally. Requires teaching teams to gitignore .pql/hooks/ and run pql init on every clone.\n  b) Use bare ''pql'' in tracked hooks; document that users must ensure pql is on git''s hook-shell PATH (e.g. add ~/.local/bin to /etc/launchd.conf or login shell startup, not just interactive shell).\n\n(a) is more robust. (b) is closer to current behaviour. Either way the abs-path baking has to go for shared clones to work cleanly. Discuss before implementing.', 'done', 'high', NULL, NULL, NULL, '2026-05-09 23:38:33', '2026-05-11 16:01:40', NULL, '17fd0897c1e4b1c418b50350abb7aa9d', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY5VVVCC5TR1WKD9TG', 'task', '06FB0TGPVYHCGT66TT5KYKNK9W', 'one-time migration: this repo''s decisions/ → governance/{decisions,questions,rejected}/', 'Migrate this repo''s own DQR tree from the flat layout to the D-21 governance layout. The migration is one-shot (runs once during this initiative) and not a permanent CLI command — downstream repos either do their own migration or set dqr_dir to keep their layout.

Steps for this repo:
  1. mkdir -p governance/{decisions,questions,rejected}
  2. mv decisions/architecture.md → governance/decisions/architecture.md (whole file; all D-records)
  3. Split decisions/questions.md by domain:
     - currently all Q records are about architecture, planning, ticket id distribution, etc.
     - go through Q-1..Q-10 and route each to governance/questions/<domain>.md based on subject (mostly architecture; some process)
  4. mv decisions/README.md → governance/README.md (or regenerate via T-35''s writer once the prologue exists)
  5. Update .gitignore: drop `!.pql/pql-plan.json` if still present (T-23 already removed it); add governance to gitignored exceptions if needed (probably not — governance/ is fully committed by design)
  6. Verify pql.db sync produces same record set after migration (29 → 29, no drift)
  7. git rm -r decisions/

Touches: filesystem mostly. Possibly a small Go helper if the Q-record split is finicky enough to need automated routing — but for 10 records, manual triage is fine.', 'done', 'medium', NULL, NULL, 'D-21', '2026-05-11 15:39:42', '2026-05-11 16:06:05', NULL, '098a8b76ff9cc2afe0f796cd090cedd8', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVYHCGT66TT5KYKNK9W', 'initiative', NULL, 'implement DQR governance layout convention', 'Bring the DQR file layout described in D-21 into pql. Move from the current flat `decisions/<file>.md` (with asymmetric `questions-X` / `rejected` prefixes) to a subdirectory structure rooted at a configurable parent (default `governance/`), with one subdirectory per record type and one file per domain inside each.

Children:
  - config knob (dqr_dir) + parser update for subdir paths
  - pql init plants the structure and writes the README prologue + auto-generated records section
  - pql decisions validate/sync gain default-on style enforcement with --no-style opt-out
  - one-time migration of this repo''s decisions/ tree to the new layout (will surface real edge cases for downstream consumers)

clide and settled-reach migrate on their own time — either by following the same shape or overriding dqr_dir to keep their existing layout.', 'done', 'medium', NULL, NULL, 'D-21', '2026-05-11 15:39:08', '2026-05-11 16:06:05', NULL, 'f8085e29b048d593cf994c6d4c7f57d1', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX39X6HKNN6KPQD5HC', 'task', '06FB0TGPVZVEJH8SZY3JJX3F8G', 'dogfood T-28: drop !.pql/hooks/ from pql repo, git rm tracked hooks', 'Apply T-28''s decision to pql''s own repo:
  1. Drop the !.pql/hooks/ exception from .gitignore (both root .gitignore and the comment block mentioning it).
  2. git rm -r .pql/hooks/ — the actual hook scripts (pre-commit, post-merge, post-checkout, post-rewrite) are per-clone content from now on.
  3. Run pql init to confirm hooks replant cleanly under the new ignore rule (they should be created, not tracked).
  4. Commit the .gitignore + tracked-file removal in one logical change.', 'done', 'medium', NULL, NULL, NULL, '2026-05-11 16:48:29', '2026-05-11 16:50:06', NULL, '30f1314633c44429e530c335a19aeca5', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXM4QPSVA336BX0WDC', 'task', '06FB0TGPVZVEJH8SZY3JJX3F8G', 'pql init: stop re-adding !.pql/pql-plan.json to managed gitignore stanza', 'Same class of issue as T-39 (tracked .pql/hooks/): pql init''s managed-gitignore stanza is out of sync with current design.

pql init unconditionally re-adds `!.pql/pql-plan.json` to the consumer''s .gitignore (internal/cli/init.go:384 — `needed` map, and :418 — emit loop). The exception dates to pre-D-15, when `pql plan export` writing pql-plan.json was the replication mechanism. D-15 / T-23 moved replication to .pql/changelog/<table>/<YYYY-MM>.sql, which is what init *should* be exempting now (and does, via `!.pql/changelog/`).

Clide hit this during the May 2026 migration: after manually removing `!.pql/pql-plan.json` from .gitignore, the next `pql init` re-added it.

Fix: drop `!.pql/pql-plan.json` from the managed list in init.go. `pql plan export` still writes the file — but it''s now a manual ad-hoc backup, not the shared replication artefact, so consumers can commit or ignore it on their own terms.

Touches:
  - internal/cli/init.go:384 (remove from `needed`)
  - internal/cli/init.go:418 (remove from emit slice)
  - possibly a test in init_test.go that asserts the entry is no longer auto-emitted
  - CHANGELOG entry: init no longer manages `!.pql/pql-plan.json`', 'done', 'medium', NULL, NULL, NULL, '2026-05-11 16:51:54', '2026-05-11 16:54:27', NULL, '35284ef1a009262c02eaaaec5172f070', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZVEJH8SZY3JJX3F8G', 'initiative', NULL, 'finish T-28: decommission tracked .pql/hooks/ across pql + pre-T-28 consumers', 'T-28 chose path (a): treat .pql/hooks/ as per-clone state and stop tracking it. The implementation only updated the gitignore *template* new init produces — pre-T-28 repos still carry !.pql/hooks/ in their .gitignore plus committed hook content with per-developer absolute pql paths baked in.

This surfaces on the first multi-developer clone of those repos: each developer''s pql init bakes a different absolute path, producing a permanent dirty diff against tracked content. clide hit it during the D-21 migration (May 2026); pql''s own repo has the same latent bug but only one developer.

Children:
  - dogfood the cleanup on pql''s own repo (drop !.pql/hooks/ from .gitignore, git rm -r .pql/hooks/, let init replant locally)
  - add a pql doctor warning when it sees !.pql/hooks/ in .gitignore *and* tracked content under .pql/hooks/ — so the next pre-T-28 repo finds out at doctor time, not at first multi-dev clone

clide is unblocked independently (drops !.pql/hooks/ and git rm''s tracked hooks on its own timetable).', 'done', 'medium', NULL, NULL, NULL, '2026-05-11 16:48:17', '2026-05-11 16:57:29', NULL, '456ffec46a0595de7539cdca8b346003', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX7M885VCZ17VKCCVW', 'task', '06FB0TGPVZVEJH8SZY3JJX3F8G', 'pql doctor: warn when !.pql/hooks/ exception present with tracked hook content', 'Add a check to pql doctor that scans .gitignore for the legacy !.pql/hooks/ exception, and if present, also checks whether .pql/hooks/* is currently tracked in git. When both are true, emit a warning explaining T-28 (hooks should be per-clone, not committed) and the cleanup steps. This catches pre-T-28 repos before they suffer first-multi-dev-clone drift.

Implementation sketch:
  - internal/cli/doctor.go (or wherever doctor lives) gains a hookExceptionCheck()
  - reads .gitignore, looks for !.pql/hooks/ (either form)
  - shells git ls-files .pql/hooks/ to detect tracked content
  - both → warning with the two-step cleanup recipe', 'cancelled', 'medium', NULL, NULL, NULL, '2026-05-11 16:48:30', '2026-05-11 16:57:29', NULL, 'e4495f67d693b029a59018ecc3afdb18', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVYNTXYTNZ263AA3DH4', 'bug', NULL, 'pql init doesn''t create .githooks/ shims for post-checkout / post-rewrite', 'Surfaced by T-25 round 2 against clide. clide uses git config core.hooksPath = .githooks/ with a shim convention (.githooks/<name> sources .pql/hooks/<name>). pql init creates the .pql/hooks/post-checkout and .pql/hooks/post-rewrite bodies but does NOT plant matching .githooks/post-checkout and .githooks/post-rewrite shims, so they never fire even though the bodies exist.\n\nensureGitHookShim is supposed to plant the shim for each hook (called via defer in installNamedHook). It plants the pre-commit and post-merge shims correctly — only the two new T-22 hooks are missed.\n\nNeeds investigation: trace ensureGitHookShim against a clide-shaped repo (core.hooksPath = .githooks/ configured). Confirm whether the issue is the resolveHooksPath logic, the shim-write logic, or something around the deferred call ordering on the new hooks. clideclaude added the two shims manually — the working clone is now correct, but the next developer to run pql init on a fresh clone would hit the same gap.', 'cancelled', 'medium', NULL, NULL, NULL, '2026-05-09 23:38:33', '2026-05-11 17:11:53', NULL, '4697af4bc915a14975f248cd022f1da6', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWAB7AHS3BXK7BYWZG', 'bug', NULL, 'pql init doesn''t upgrade existing pre-T-22 hook content via replaceHookBlock', 'Surfaced by T-25 round 2 against clide. Existing .pql/hooks/pre-commit and .pql/hooks/post-merge from older pql versions were left untouched by pql init — clideclaude had to rm and re-run init to get the new hook bodies.\n\nThe replaceHookBlock helper in internal/cli/init.go (added in T-22) is supposed to find the (start-marker, end-marker) span and replace just the pql-managed block while preserving any user content outside. There''s a unit test (TestInstallNamedHook_UpgradesExistingHook) that passes in isolation, but the real-world case against clide didn''t trigger the upgrade.\n\nPossible causes:\n  - The legacy hook had a different start/end marker style than the current code expects.\n  - replaceHookBlock has a subtle bug that the test fixture doesn''t exercise.\n  - installNamedHook''s no-op short-circuit (if updated == existing return early) returned early even when content differed (a hash earlier in the session also showed installed: false, existed: true under suspicious conditions).\n\nNeeds investigation: clone clide pre-migration state, run pql init under v1.4.27+ (with whatever fix), confirm hook content updates without manual rm.', 'done', 'medium', NULL, NULL, NULL, '2026-05-09 23:38:33', '2026-05-11 19:18:04', NULL, 'e18ed314624781d78599569915851db3', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX68TB56C230B934J8', 'initiative', NULL, 'Collapse zero-matches to exit 0; retire exit 2', 'Zero matches now exits 0 with an empty [] instead of exit 2 (NoMatch), which is retired. The empty result lives in the data, never the exit code, so callers treating non-zero as failure stop flagging empty results as errors. Shipped in commit ef73d6e: internal/diag drops NoMatch, all subcommands return success on empty, docs/SKILL/CLAUDE updated, integration tests flipped to exit 0.', 'done', 'medium', NULL, NULL, 'D-22', '2026-05-25 09:41:58', '2026-05-25 09:42:17', NULL, '31e48b95f0c26d23481715d64c01f88c', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXFR50CH4QFHZEK20R', 'task', '06FB0TGPVYHCGT66TT5KYKNK9W', 'add dqr_dir config knob with governance default', 'Add a `dqr_dir` field to .pql/config.yaml (per-vault), defaulting to `governance/` when absent. config.Load surfaces it; every command that walks DQR markdown reads it instead of hardcoding ''decisions/''. Existing pql/clide/settled-reach repos with the legacy layout can set `dqr_dir: decisions` (or whatever they used) to keep working without migrating.

Touches: internal/config/{config.go, defaults}, the call sites in cli/decisions.go and cli/init.go that resolve the DQR path. Tests: config unmarshal default, override via yaml, env var (PQL_DQR_DIR? — match the existing PQL_* env convention if there is one).', 'done', 'medium', NULL, NULL, 'D-21', '2026-05-11 15:39:42', '2026-05-31 11:26:57', NULL, '123820829e392c7aab1fe93acae201d2', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX1V2YZ5NYCQTFSYVC', 'task', '06FB0TGPVYHCGT66TT5KYKNK9W', 'pql decisions validate / sync gain default-on style enforcement', 'Extend validate (currently checks duplicate IDs, empty titles, broken refs) with the convention checks from D-21:

  - Filename style: lowercase, hyphenated, .md extension. Warn on uppercase / spaces / underscores.
  - Subdir-type consistency: every record in `<dqr_dir>/decisions/X.md` is a D-record (heading prefix matches); every record in `questions/` is Q; etc. Warn on mixed.
  - Stale README: records exist in pql.db that aren''t in the README, or vice versa. Warn with ''run pql decisions sync to regenerate''.
  - Domain pairing (informational): if `questions/foo.md` exists, `decisions/foo.md` probably should too. Info-level, not warn.
  - Conflicting domains: two files in different subdirs claiming the same domain stem is fine; two files in the same subdir with similar names (`arch.md` and `architecture.md`) is an error.

Warnings emit on stderr per the existing diag.Diag pattern, exit zero. Errors exit 65. `--no-style` suppresses warnings (errors remain).

pql decisions sync runs the same style checks during its parse pass and surfaces the warnings — so authors who never explicitly run validate still see drift the first time they sync after an edit.

Touches: internal/planning/parser/decisions.go (style check hooks), internal/cli/decisions.go (validate verb body + new flag), wired from sync too. Tests: each rule fires on a constructed fixture; --no-style suppresses; errors still emit at non-zero exit.', 'done', 'medium', NULL, NULL, 'D-21', '2026-05-11 15:39:42', '2026-05-31 11:26:57', NULL, '8096c93f107d77ec8b6722b013112019', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY5MS4E99PAWQGCNGR', 'task', '06FB0TGPVYHCGT66TT5KYKNK9W', 'parser: infer record type from subdirectory, domain from filename stem', 'Extend internal/planning/parser/decisions.go to walk `<dqr_dir>/{decisions,questions,rejected}/<domain>.md` and infer:
  - record type from the immediate parent directory (decisions → confirmed, questions → question, rejected → rejected)
  - domain from the filename stem (no `questions-` / `rejected` prefix handling — that convention is retired)

The current parseText already uses heading-prefix (D|Q|R) for type; this becomes a sanity check (file says ''questions/'', heading says ''D-'' → warn or error). Backward-compat: if dqr_dir points at the legacy flat layout (no subdirs found), fall back to the existing domainFromFilename logic so consumers that haven''t migrated still work.

Touches: internal/planning/parser/decisions.go (path-walking, type inference). Tests: subdir + flat both parse; type/subdir mismatch surfaces; domain extracted correctly across both layouts.', 'done', 'medium', NULL, NULL, 'D-21', '2026-05-11 15:39:42', '2026-05-31 11:26:57', NULL, 'd821dd2f0517bcfca367eb62281aebae', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXTXAN0CRFMFNHB670', 'task', '06FB0TGPVYHCGT66TT5KYKNK9W', 'pql init plants governance/ structure + README with auto-generated records section', 'Extend internal/cli/init.go to plant the new layout on a fresh repo:

  1. Create `<dqr_dir>/{decisions,questions,rejected}/` (defaults to governance/). No domain files pre-created.
  2. Write `<dqr_dir>/README.md` if absent. Two zones in the file:
     - Prologue (human-edited; written once, never overwritten): briefly describes the DQR mechanism, links to pql docs, lists the five recommended canonical domains (architecture, process, design, coding-conventions, testing), and a ''common additions'' line (accessibility, security, licensing, documentation, deployment, performance).
     - Auto-generated records section delimited by `<!-- pql:records (auto-generated; do not edit manually) -->`. Initial sync after init populates this from current pql.db state.

Sync-time regen: `pql decisions sync` also rewrites the records section so the README stays current as records land. The prologue is left alone.

Migration affordance: if .pql/config.yaml''s dqr_dir is unset and `decisions/` exists with markdown content, pql init detects the legacy layout and emits a clear stderr message pointing at the migration helper (T-37) rather than silently planting a parallel governance/ tree.

Touches: internal/cli/init.go (new init step + README writer), possibly internal/planning/repo/decisions.go (a ListAll for the README pass). Tests: fresh init plants the three subdirs + README with prologue + auto section; re-init is idempotent; legacy-decisions/ trips the migration message.', 'done', 'medium', NULL, NULL, 'D-21', '2026-05-11 15:39:42', '2026-05-31 11:26:57', NULL, 'eef7aeb0592cf86d2c52c2b50d004f81', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXWVVHST6374CJDB8R', 'task', NULL, 'implement pql.db forward migrations (gate: third-party distribution)', 'Per the 2026-05-31 amendment to D-19: the ''no migration runner ever'' stance holds only while pql is single-author / pre-distribution — pql.db is a regenerable cache, so rm + rebuild from the changelog is acceptable recovery. Before distributing to third parties or onboarding users beyond the author, add an in-place forward-migration path: external users can''t be told to rm pql.db on every schema change, and their pql.db may hold state not yet in any shared changelog. Scope: revive the in-house runner D-6 sketched (a schema_migrations table + forward-only steps in internal/planning/schema.go), or equivalent. Gate: external distribution / multi-user adoption. Until then, schema-create-if-missing + verify + regenerate-from-changelog stands.', 'backlog', 'medium', NULL, NULL, 'D-19', '2026-05-31 12:25:23', '2026-05-31 12:25:23', NULL, 'bfeb8df414377f34a694d4bf999bba3f', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWP9K57RN07XE8HQ14', 'task', '06FB0TGPVYHCGT66TT5KYKNK9W', 'DQR layout leftovers: PQL_DQR_DIR env + domain-pairing checks', 'Residual sub-bullets from T-33/T-36, verified unshipped after the D-21 layout landed in f167f4c (core feature is live):

- T-33 leftover: PQL_DQR_DIR env var override for dqr_dir, matching the PQL_VAULT/PQL_DB/PQL_CONFIG convention. Only the .pql/config.yaml `dqr_dir` knob exists today. (T-33 flagged this as tentative with a ''?''.)
- T-36 leftover: two style checks not yet implemented — (a) informational domain-pairing hint (questions/<d>.md present ⇒ decisions/<d>.md probably should be too), and (b) conflicting-similar-domains error (e.g. arch.md and architecture.md in the same subdir). Filename-style and subdir-type-mismatch warnings already land.

Low priority; the layout works without these.', 'done', 'low', NULL, NULL, 'D-21', '2026-05-31 11:26:57', '2026-05-31 12:57:41', NULL, '8cef2c0dc29bffc4b526fc502341bda4', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at >= tickets.updated_at;
