INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWCA6PCMMPYMPD1SB8', 'task', '06FB0TGPVY4DA9DZX232RFV8RW', 'Add ''ticket new --id-only'' for tree-creation scripts (#5)', NULL, 'backlog', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '2f00333a65e0457299c604cee30c8d06', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX3K7HXJJ8KDD2XGBG', 'task', '06FB0TGPVY4DA9DZX232RFV8RW', 'Regression tests: resolved-question index idempotency + skill/binary flag parity (#6/#7)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '694d1444a824dadae81969806b3e3c2d', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWZQEJD6Z7SJ04HPNW', 'task', '06FB0TGPVY4DA9DZX232RFV8RW', 'Rewrite schema-mismatch recovery hint (#3/#4)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '6a9bec49534196a68277ffb39f2bd87d', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVX7DYM1JWZYA3T6YCG', 'task', '06FB0TGPVY4DA9DZX232RFV8RW', 'Fix embedded skill durability section (#2)', NULL, 'done', 'medium', NULL, NULL, NULL, '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '81fc356f06a311cdbbd4cb5b121284d2', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZ46NJ0MDJEFYBD7T0', 'task', '06FB0TGPVY4DA9DZX232RFV8RW', 'Write-through ticket mutations to the changelog (#1)', NULL, 'done', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:35', NULL, '9dc02a6d3e0c9e840494c772a4454950', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVY4DA9DZX232RFV8RW', 'initiative', NULL, 'Act on live-session improvement briefing (pql-improvements.md)', NULL, 'done', 'medium', NULL, NULL, 'D-23', '2026-06-03 14:41:35', '2026-06-03 14:41:36', NULL, '1025d28fdc1a8e50e19fe4a689607e31', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZG6A02Y64G4QSM4Y0', 'task', NULL, 'Unify .githooks shim tracking: post-checkout/post-rewrite still tracked, pre-commit/post-merge ignored', 'The four pql replication hook shims in .githooks/ are tracked inconsistently:

  - .githooks/post-checkout  -> TRACKED (git ls-files)
  - .githooks/post-rewrite   -> TRACKED
  - .githooks/pre-commit     -> gitignored (.gitignore L65)
  - .githooks/post-merge     -> gitignored (.gitignore L66)

All four are functionally identical static two-line shims (git rev-parse + source .pql/hooks/<name>); none bakes a per-developer path (that lives in the .pql/hooks/* bodies, correctly ignored under .pql/*). So the split is unintended drift, not a real distinction. (pre-push is legitimately tracked -- it is the hand-authored lint gate, not a replication shim.)

History: T-28/T-38/T-39 settled that hook scripts + shims are per-clone, planted by ''pql init'', not tracked; T-39 git-rm''d .pql/hooks/ and dropped the !.pql/hooks/ exception. T-30 (cancelled) records that ensureGitHookShim is supposed to plant ALL FOUR .githooks/ shims and that post-checkout/post-rewrite were the ones being missed. The tracked post-checkout/post-rewrite shims are the leftover that escaped the T-39 cleanup, and .gitignore lacks matching ignore rules for them.

Impact: latent. A fresh clone that only runs ''git config core.hooksPath .githooks'' (without ''pql init'') gets pre-push + the two tracked rebuild shims, but NOT pre-commit/post-merge -- so write-through staging and post-merge import silently don''t fire until init runs. The asymmetry also makes the per-clone-hooks invariant (T-28) ambiguous.

Proposed resolution (align to the settled per-clone policy): git rm .githooks/post-checkout and .githooks/post-rewrite, add them to the .gitignore stanza alongside pre-commit/post-merge, and ensure ''pql init'' (ensureGitHookShim) reliably plants all four shims. Confirm a fresh clone + ''pql init'' + core.hooksPath=.githooks yields the full lifecycle with a clean tree. Alternatively, if committed shims are deemed desirable for zero-init clones, commit all four and document why -- but that contradicts T-28/T-39, so it would need a D-18 amendment.

Surfaced 2026-06-05 while wiring core.hooksPath on the pql repo: pre-commit/post-merge were absent from the active hook set until ''pql init'' planted them.

Resolved 2026-06-05. No code change needed: pql init''s ensureGitHookShim already plants all four shims into the resolved core.hooksPath dir. Fix was repo-state alignment: git rm --cached .githooks/post-checkout and post-rewrite, extended the .gitignore stanza to ignore all four replication shims (rationale: a non-pql contributor must be able to use the repo without pql hook machinery in their tree), and documented the set-hooksPath-before-init ordering in CLAUDE.md. pre-push stays tracked (project CI gate, not a pql shim). Verified end-to-end on a fresh clone: only pre-push tracked; after core.hooksPath=.githooks + pql init all four shims plant with a clean tree and the hooks fire. Committed in adf44e3.', 'in_progress', 'medium', NULL, NULL, 'D-18', '2026-06-05 10:44:32', '2026-06-05 11:15:00', NULL, '389271ffff251a98175536ddedaccceb', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVXV1MC0K3V66HAVM6C', 'task', NULL, 'Don''t narrate changelog-dirty after ticket mutations', 'A `pql ticket` change (create / status transition) leaves `.pql/changelog/` dirty; the auto-commit hook persists it on the next `git commit`. This is known and expected behavior — the pre-commit hook stages `.pql/changelog/` so it lands in the same commit as the change that produced it.

Don''t narrate "the ticket won''t persist until committed" on every ticket edit. Either quietly fold the bookkeeping into a commit or trust the normal commit flow.', 'done', 'medium', NULL, NULL, NULL, '2026-06-06 08:48:11', '2026-06-06 08:48:16', NULL, '3e68269dd782a61432d0d21c73c4838b', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVWJ2JAZDR28XCK6FJR', 'task', NULL, 'implement or formally defer documented DSL grammar surface', 'docs/pql-grammar.md documents operators/functions that are not implemented, so documented examples error at runtime (surfaced by the 2026-05-31 docs-vs-code audit): (1) REGEXP — parser emits it but no UDF is registered (only ''reverse'' in internal/store/udf.go), so ''name REGEXP ...'' fails with ''no such function'' (exit 70); (2) functions contains/position/slice/dirname/basename/extension/now()/today() and cast(x AS type) are absent from functionMap (internal/query/dsl/eval/compile.go) and CAST has no parse rule; (3) array columns inside length()/array fns error with bare_array_ref. Either implement these (register REGEXP UDF, add the functions + a CAST parse rule, allow array fns in projections) or keep them deferred. Interim: docs/pql-grammar.md has been marked ''planned'' for the unimplemented parts; this ticket tracks closing the gap for real.', 'backlog', 'medium', NULL, NULL, NULL, '2026-05-31 12:25:23', '2026-06-08 15:40:16', NULL, '70d60374116921d241263fff9143c0ef', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB0TGPVZZMVVQQD49BEHHXXR', 'task', NULL, 'Surface ticket-ID collisions loudly at changelog replay', 'Ticket IDs are allocated as max(existing)+1 against the *local* changelog, so two clones/branches/sessions that file between syncs can both pick the same T-NNN. This is an accepted cost of sequential IDs with no central authority (git provisions none) — we don''t want to prevent it.

The real hazard is that it''s currently *silent*: `tickets` replays with `ON CONFLICT(id) DO UPDATE`, so two unrelated tickets claiming one id merge into a single row (higher updated_at/hash wins) with no error. The corruption is invisible until someone notices a wrong title.

Make it loud instead of preventing it: at changelog replay / `pql plan rebuild`, detect when one `id` is claimed by two distinct `hash` lineages (different created_at/title for the same id) and surface it as a diagnostic rather than letting the upsert paper over it. Keeps sequential human-readable IDs; turns invisible merge into a rebuild-time warning the maintainer can reconcile by re-filing one under a fresh id.

Context: hit live on 2026-06-06 — local T-52 collided with an already-pushed remote T-52, resolved by re-filing as T-53.', 'done', 'medium', NULL, NULL, NULL, '2026-06-06 08:53:46', '2026-06-09 07:06:12', NULL, '9d6c423eba5d7001241c676f307afe49', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB1DY5GCYESVQKG78GNTCRJW', 'bug', NULL, 'pql.db SQLITE_BUSY (exit 69) under concurrent writes', 'busy_timeout was set per-connection via PRAGMA but the database/sql pool was unbounded, so a write on a fresh pooled connection (busy_timeout=0) failed immediately with SQLITE_BUSY when another process (e.g. a git hook firing pql) held the write lock. Fixed in 1.10.2 by capping the planning + index DB pools at one connection (SetMaxOpenConns(1)) so the busy_timeout-bearing connection is authoritative. Surfaced by clide''s concurrent real-pql tests. Guarded by TestOpenPath_SingleConnection + TestConcurrentCreate_NoBusy.', 'backlog', 'medium', NULL, NULL, NULL, '2026-06-10 08:48:14', '2026-06-10 08:48:14', NULL, 'd2a61e8d68dbadfde79ac31813adf6c6', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
INSERT INTO tickets (record_id, type, parent_record_id, title, description, status, priority, assigned_to, team, decision_ref, created_at, updated_at, deleted_at, hash, canonical_version) VALUES ('06FB1DY5GCYESVQKG78GNTCRJW', 'bug', NULL, 'pql.db SQLITE_BUSY (exit 69) under concurrent writes', 'busy_timeout was set per-connection via PRAGMA but the database/sql pool was unbounded, so a write on a fresh pooled connection (busy_timeout=0) failed immediately with SQLITE_BUSY when another process (e.g. a git hook firing pql) held the write lock. Fixed in 1.10.2 by capping the planning + index DB pools at one connection (SetMaxOpenConns(1)) so the busy_timeout-bearing connection is authoritative. Surfaced by clide''s concurrent real-pql tests. Guarded by TestOpenPath_SingleConnection + TestConcurrentCreate_NoBusy.', 'done', 'medium', NULL, NULL, NULL, '2026-06-10 08:48:14', '2026-06-10 08:48:14', NULL, '17cc68e9be46b8df431308f39a5943dc', 2) ON CONFLICT(record_id) DO UPDATE SET type=excluded.type, parent_record_id=excluded.parent_record_id, title=excluded.title, description=excluded.description, status=excluded.status, priority=excluded.priority, assigned_to=excluded.assigned_to, team=excluded.team, decision_ref=excluded.decision_ref, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, hash=excluded.hash, canonical_version=excluded.canonical_version WHERE excluded.updated_at > tickets.updated_at OR (excluded.updated_at = tickets.updated_at AND excluded.hash > tickets.hash);
